# Generated by Django 3.1.2 on 2020-12-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('api_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.restaurant'),
        ),
        migrations.AddField(
            model_name='drink',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_code', on_delete=django.db.models.deletion.CASCADE, to='auth_app.restaurant'),
        ),
        migrations.AddField(
            model_name='dish_ingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.dish'),
        ),
        migrations.AddField(
            model_name='dish_ingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(through='api_admin.Dish_Ingredient', to='api_admin.Ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.restaurant'),
        ),
    ]
