# Generated by Django 3.1.2 on 2020-12-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0002_auto_20201205_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='ref',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
