# Generated by Django 3.1.2 on 2020-11-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_auto_20201110_2126'),
        ('api_admin', '0005_auto_20201110_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='static/not-image.png', upload_to='dishes/%Y/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.restaurant'),
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='Ingredient',
        ),
    ]
