# Generated by Django 3.1.2 on 2020-11-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0006_auto_20201120_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='not-image.png', upload_to='dishes/%Y/'),
        ),
    ]
