# Generated by Django 3.1.2 on 2020-12-05 15:44
from datetime import date
from django.db import migrations

today = date.today()
date_today = today.strftime("%Y/%m/%d")


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            [('INSERT INTO public."Position" (name , state, created_at , updated_at ) VALUES (%s , %s, %s, %s);', [
              'Chef', "1", date_today, date_today])],
        ),
        migrations.RunSQL(
            [('INSERT INTO public."Position" (name , state, created_at , updated_at ) VALUES (%s , %s, %s, %s);', [
              'Waiter', "1", date_today, date_today])],
        ),
        migrations.RunSQL(
            [('INSERT INTO public."Position" (name , state, created_at , updated_at ) VALUES (%s , %s, %s, %s);', [
              'Admin', "1", date_today, date_today])],
        ),
    ]
