# Generated by Django 3.1.2 on 2020-10-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_position_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='code',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
