# Generated by Django 3.1.2 on 2020-11-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_user22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user22',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
