# Generated by Django 3.1.2 on 2020-11-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_auto_20201103_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user22',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
