# Generated by Django 3.1.2 on 2020-11-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_auto_20201103_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user22',
            old_name='restaurant_code',
            new_name='restaurant',
        ),
        migrations.RemoveField(
            model_name='user22',
            name='full_name',
        ),
    ]
