# Generated by Django 3.1.2 on 2020-11-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_auto_20201103_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user22',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.position'),
        ),
        migrations.AlterField(
            model_name='user22',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.restaurant'),
        ),
    ]
