# Generated by Django 3.1.2 on 2020-11-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_app', '0012_auto_20201103_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User22',
            new_name='CustomUser',
        ),
    ]
