# Generated by Django 3.2.4 on 2021-06-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('code', models.CharField(error_messages={'unique': 'The code entered is already registered, please try another'}, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('total', models.BigIntegerField(blank=True, default=0)),
                ('action', models.SmallIntegerField(default=1)),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Order_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(db_column='order_code', on_delete=django.db.models.deletion.CASCADE, to='api_waiter.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order_User',
            },
        ),
        migrations.CreateModel(
            name='Order_Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.drink')),
                ('order', models.ForeignKey(db_column='order_code', on_delete=django.db.models.deletion.CASCADE, to='api_waiter.order')),
            ],
            options={
                'db_table': 'Order_Drinks',
            },
        ),
        migrations.CreateModel(
            name='Order_Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.dish')),
                ('order', models.ForeignKey(db_column='order_code', on_delete=django.db.models.deletion.CASCADE, to='api_waiter.order')),
            ],
            options={
                'db_table': 'Order_Dish',
            },
        ),
        migrations.CreateModel(
            name='Order_Complement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.complement')),
                ('order', models.ForeignKey(db_column='order_code', on_delete=django.db.models.deletion.CASCADE, to='api_waiter.order')),
            ],
            options={
                'db_table': 'Order_Complement',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='complement',
            field=models.ManyToManyField(through='api_waiter.Order_Complement', to='api_admin.Complement'),
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(through='api_waiter.Order_Dish', to='api_admin.Dish'),
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(through='api_waiter.Order_Drinks', to='api_admin.Drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.CASCADE, to='api_admin.table'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(through='api_waiter.Order_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
