# Generated by Django 3.1.2 on 2020-12-05 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_waiter', '0001_initial'),
        ('api_admin', '0002_auto_20201205_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_drinks',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.drink'),
        ),
        migrations.AddField(
            model_name='order_drinks',
            name='order',
            field=models.ForeignKey(db_column='order_code', on_delete=django.db.models.deletion.CASCADE, to='api_waiter.order'),
        ),
        migrations.AddField(
            model_name='order_dish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.dish'),
        ),
        migrations.AddField(
            model_name='order_dish',
            name='order',
            field=models.ForeignKey(db_column='order_code', on_delete=django.db.models.deletion.CASCADE, to='api_waiter.order'),
        ),
        migrations.AddField(
            model_name='order_complement',
            name='complement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.complement'),
        ),
        migrations.AddField(
            model_name='order_complement',
            name='order',
            field=models.ForeignKey(db_column='order_code', on_delete=django.db.models.deletion.CASCADE, to='api_waiter.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='complement',
            field=models.ManyToManyField(through='api_waiter.Order_Complement', to='api_admin.Complement'),
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(through='api_waiter.Order_Dish', to='api_admin.Dish'),
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(through='api_waiter.Order_Drinks', to='api_admin.Drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.CASCADE, to='api_admin.table'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(through='api_waiter.Order_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
