# Generated by Django 3.1.2 on 2020-12-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_waiter', '0002_auto_20201205_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='active',
            new_name='action',
        ),
    ]
